source "https://api.berkshelf.com"

cookbook 'chef-solo-search', git: 'https://github.com/edelight/chef-solo-search'
cookbook 'git'
cookbook 'user'
cookbook 'sudo'
cookbook 'ntp'
cookbook 'virtualbox'
cookbook 'vagrant', git: 'https://github.com/jtimberman/vagrant-cookbook.git'
cookbook 'os-hardening', git: 'https://github.com/TelekomLabs/chef-os-hardening'
cookbook 'ssh-hardening', git: 'https://github.com/TelekomLabs/chef-ssh-hardening'
cookbook 'nginx'
cookbook 'docker', git: 'https://github.com/bflad/chef-docker'
cookbook 'zsh', git: 'https://github.com/arlimus/chef-zsh.git'
cookbook 'openvpn'
